version: "2"
services: 
    dev:
        container_name: "bots_trading"
        image: "tagsdetail"
        build: 
            context: .
            dockerfile: Dockerfile
        ports: 
          - "3000:3000"
        volumes: 
          -  ./:/app